# Site Configuration - Control visibility of sections
sections:
  workExperience: true
  talks: true
  writing: true
  socialLinks: true

# Individual elements
elements:
  avatar: true
  themeSwitch: true
  header: true
  footer: true
